// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRMdJvE_E2bszvYuxWDWmrkhzInuJJ4mI',
    appId: '1:878979654083:web:609b0e478a764f2e081d76',
    messagingSenderId: '878979654083',
    projectId: 'loginn3-b53ef',
    authDomain: 'loginn3-b53ef.firebaseapp.com',
    storageBucket: 'loginn3-b53ef.firebasestorage.app',
    measurementId: 'G-B5VTSXX3J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAm6riORe-pUboqYljfwqu6oPIQZrS4sA',
    appId: '1:878979654083:android:195845bb8d235900081d76',
    messagingSenderId: '878979654083',
    projectId: 'loginn3-b53ef',
    storageBucket: 'loginn3-b53ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4zOhTMl6noGT8b8ABsXqwXbrUqwMduSQ',
    appId: '1:878979654083:ios:411e33578893b8b5081d76',
    messagingSenderId: '878979654083',
    projectId: 'loginn3-b53ef',
    storageBucket: 'loginn3-b53ef.firebasestorage.app',
    androidClientId: '878979654083-864p72sd3mnb0t82ek3egdn6hjabklf7.apps.googleusercontent.com',
    iosClientId: '878979654083-ekikon8s1ss50a5731d3pv92gh4b7qhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginn3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4zOhTMl6noGT8b8ABsXqwXbrUqwMduSQ',
    appId: '1:878979654083:ios:411e33578893b8b5081d76',
    messagingSenderId: '878979654083',
    projectId: 'loginn3-b53ef',
    storageBucket: 'loginn3-b53ef.firebasestorage.app',
    androidClientId: '878979654083-864p72sd3mnb0t82ek3egdn6hjabklf7.apps.googleusercontent.com',
    iosClientId: '878979654083-ekikon8s1ss50a5731d3pv92gh4b7qhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginn3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRMdJvE_E2bszvYuxWDWmrkhzInuJJ4mI',
    appId: '1:878979654083:web:8161cf4e053c6e69081d76',
    messagingSenderId: '878979654083',
    projectId: 'loginn3-b53ef',
    authDomain: 'loginn3-b53ef.firebaseapp.com',
    storageBucket: 'loginn3-b53ef.firebasestorage.app',
    measurementId: 'G-89EQ4ETHRW',
  );

}